### ISSUE TITLE
Crash sur le RsaAesCryptoManager en API 17

### ISSUE THREAD

**Issue by ghost** [MobileTribe/pandroid#2]
J'utilise le CryptoManager et son implementation RsaAesCryptoManager, j'ai un crash lorsque j'utilise la méthode asymmetricEncrypt sur Android Android 4.2 (API 17). Voici la stacktrace que j'obtiens : 

readKey: Read an exception; java.io.NotSerializableException: org.apache.harmony.xnet.provider.jsse.OpenSSLKey
                                                                                                        java.io.WriteAbortedException: Read an exception; java.io.NotSerializableException: org.apache.harmony.xnet.provider.jsse.OpenSSLKey
                                                                                                            at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:804)
                                                                                                            at java.io.ObjectInputStream.readObject(ObjectInputStream.java:2013)
                                                                                                            at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1970)
                                                                                                            at java.io.ObjectInputStream.readFieldValues(ObjectInputStream.java:1141)
                                                                                                            at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:455)
                                                                                                            at java.io.ObjectInputStream.readObjectForClass(ObjectInputStream.java:1373)
                                                                                                            at java.io.ObjectInputStream.readHierarchy(ObjectInputStream.java:1270)
                                                                                                            at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1865)
                                                                                                            at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:787)
                                                                                                            at java.io.ObjectInputStream.readObject(ObjectInputStream.java:2013)
                                                                                                            at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1970)
                                                                                                            at java.io.ObjectInputStream.readFieldValues(ObjectInputStream.java:1141)
                                                                                                            at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:455)
                                                                                                            at java.io.ObjectInputStream.readObjectForClass(ObjectInputStream.java:1373)
                                                                                                            at java.io.ObjectInputStream.readHierarchy(ObjectInputStream.java:1270)
                                                                                                            at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1865)
                                                                                                            at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:787)
                                                                                                            at java.io.ObjectInputStream.readObject(ObjectInputStream.java:2013)
                                                                                                            at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1970)
                                                                                                            at com.leroymerlin.pandroid.security.RsaAesCryptoManager.readKey(RsaAesCryptoManager.java:84)
                                                                                                            at com.leroymerlin.pandroid.security.RsaAesCryptoManager.asymmetricEncrypt(RsaAesCryptoManager.java:146)
                                                                                                            at com.smarthome.globals.manager.impl.SettingManagerImpl$1.onResponse(SettingManagerImpl.java:81)
                                                                                                            at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
                                                                                                            at android.os.Handler.handleCallback(Handler.java:725)
                                                                                                            at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                                                            at android.os.Looper.loop(Looper.java:137)
                                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                                            at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                                                                            at dalvik.system.NativeStart.main(Native Method)
                                                                                                         Caused by: java.io.NotSerializableException: org.apache.harmony.xnet.provider.jsse.OpenSSLKey

**Comment by paillardf** [comment]
Fix in 2.0.1
